# vim:fileencoding=utf-8:foldmethod=marker

# : App {{{

[app]
overall = { bg = "#181A1C" }

# : }}}


# : Manager {{{

[mgr]
cwd = { fg = "#AEE6F0" }

# Find
find_keyword  = { fg = "#EBC56C", bold = true, italic = true, underline = true }
find_position = { fg = "#C1A9E8", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#4FA3C0", bg = "#4FA3C0" }
marker_cut      = { fg = "#F07E9F", bg = "#F07E9F" }
marker_marked   = { fg = "#F2A49E", bg = "#F2A49E" }
marker_selected = { fg = "#EBC56C", bg = "#EBC56C" }

# Count
count_copied   = { fg = "#E9F2F2", bg = "#4FA3C0" }
count_cut      = { fg = "#E9F2F2", bg = "#F07E9F" }
count_selected = { fg = "#181A1C", bg = "#EBC56C" }

# Border
border_symbol = "│"
border_style  = { fg = "#33383C" }

# Highlighting
syntect_theme = ""

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#E9F2F2", bg = "#4FA3C0", bold = true }
inactive = { fg = "#4FA3C0", bg = "#E9F2F2" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#181A1C", bg = "#AEE6F0", bold = true }
normal_alt  = { fg = "#181A1C", bg = "#E9F2F2", bold = true }

# Select mode
select_main = { fg = "#181A1C", bg = "#F07E9F", bold = true }
select_alt  = { fg = "#181A1C", bg = "#E9F2F2", bold = true }

# Unset mode
unset_main = { fg = "#181A1C", bg = "#F07E9F", bold = true }
unset_alt  = { fg = "#181A1C", bg = "#E9F2F2", bold = true }

# : }}}


# : Indicator of hovered file {{{

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "", close = "" }

# : }}}


# : Status bar {{{

[status]
overall   = { bg = "#181A1C" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#586266" }
perm_type  = { fg = "#C1A9E8" }
perm_read  = { fg = "#EBC56C" }
perm_write = { fg = "#F07E9F" }
perm_exec  = { fg = "#AEE6F0" }

# Progress
progress_label  = { fg = "#E9F2F2", bold = true }
progress_normal = { fg = "#4FA3C0", bg = "#1B1E20" }
progress_error  = { fg = "#F07E9F", bg = "#1B1E20" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#1F2225" }
cand            = { fg = "#AEE6F0" }
rest            = { fg = "#586266" }
desc            = { fg = "#EBC56C" }
separator       = "  "
separator_style = { fg = "#586266" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#33383C" }
title      = { fg = "#F07E9F", bold = true }
body       = { fg = "#E9F2F2" }
list       = { fg = "#E9F2F2" }
btn_yes    = { fg = "#181A1C", bg = "#4FA3C0", bold = true }
btn_no     = { fg = "#181A1C", bg = "#E9F2F2", bold = true }
btn_labels = [ "  [y]es  ", "  (n)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#33383C" }
title  = { fg = "#AEE6F0", bold = true }

# Table
tbl_col  = { fg = "#AEE6F0" }
tbl_cell = { fg = "#181A1C", bg = "#EBC56C", bold = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#4FA3C0" }
title_warn  = { fg = "#EBC56C" }
title_error = { fg = "#F07E9F" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#4FA3C0" }
active   = { fg = "#C1A9E8", bold = true }
inactive = { fg = "#859296" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#4FA3C0" }
title    = { bold = true }
value    = { fg = "#E9F2F2" }
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#4FA3C0" }
active   = { bg = "#E9F2F2", fg = "#181A1C", bold = true }
inactive = { fg = "#859296" }

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#4FA3C0" }
title   = { bold = true }
hovered = { fg = "#C1A9E8", bold = true, reversed = true }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "#AEE6F0" }
run     = { fg = "#C1A9E8" }
desc    = { fg = "#EBC56C" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#181A1C", bg = "#E9F2F2" }

# : }}}


# : File-specific styles {{{

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#C1A9E8" },

  # Media
  { mime = "{audio,video}/*", fg = "#EBC56C" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#F07E9F" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#F2A49E" },

  # Empty files
  # { mime = "inode/empty", fg = "#F07E9F" },

  # Special files
  { url = "*", is = "orphan", fg = "#181A1C", bg = "#F07E9F" },
  { url = "*", is = "exec", fg = "#AEE6F0" },

  # Dummy files
  { url = "*", is = "dummy", fg = "#181A1C", bg = "#F07E9F" },
  { url = "*/", is = "dummy", fg = "#181A1C", bg = "#F07E9F" },

  # Fallback
  { url = "*", fg = "#E9F2F2" },
  { url = "*/", fg = "#4FA3C0" }
]

# : }}}
