include paragon.conf

font_family      Ioskeley Mono Medium
font_size 13.0
disable_ligatures always 

cursor_shape block 
cursor_blink_interval 0

scrollback_lines 2000
scrollbar never
wheel_scroll_multiplier 5.0
pixel_scroll true

mouse_hide_wait 3.0
copy_on_select no
select_by_word_characters @-./_~?&=%+#
click_interval -1.0

repaint_delay 10
input_delay 3
sync_to_monitor yes

enable_audio_bell no

remember_window_size  yes
enabled_layouts *           
window_border_width 0      
placement_strategy center 
hide_window_decorations yes

shell .                              
editor .                            
shell_integration enabled          
allow_hyperlinks yes                 

clear_all_shortcuts yes  
map kitty_mod+equal  change_font_size all +1.0
map kitty_mod+minus  change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+e open_url_with_hints

confirm_os_window_close 0
shell sh -c "tmux new-session -A -s master"
