background               #181A1C
foreground               #DCE5E5
selection_foreground     #DCE5E5
selection_background     #33383D

cursor                   #DCE5E5
cursor_text_color        #181A1C

url_color                #ECA25C

active_tab_foreground    #DCE5E5
active_tab_background     #181A1C
inactive_tab_foreground  #4B5B63
inactive_tab_background   #1E2124

active_border_color      #282B2F
inactive_border_color    #33383D

color0   #131416
color8   #33383D
color1   #E66B80
color9   #EDABB6
color2   #5FC878
color10  #98D6A7
color3   #ECA25C
color11  #F0C79F
color4   #A1DEEA
color12  #D5EAEF
color5   #5AA6E6
color13  #9CC7EC
color6   #5FD3BB
color14  #9BDED0
color7   #DCE5E5
color15  #F3F6F6
