background               #181A1C
foreground               #E9F2F2
selection_foreground     #E9F2F2
selection_background     #33383C

cursor                   #E9F2F2
cursor_text_color        #181A1C

url_color                #D9CC58

active_tab_foreground    #E9F2F2
active_tab_background    #181A1C
inactive_tab_foreground  #6E797E
inactive_tab_background  #1F2225

active_border_color      #272C2F
inactive_border_color    #33383C

color0   #131618
color8   #33383C
color1   #E0617A
color9   #F1738D
color2   #8FCF7A
color10  #9FDC8A
color3   #D9CC58
color11  #E6D667
color4   #A5E9F5
color12  #B7F2FC
color5   #D78CF0
color13  #E39AF8
color6   #46C2A8
color14  #5FD3BA
color7   #E9F2F2
color15  #F5FAFA
