#!/usr/bin/env bash

# Verificar si se está ejecutando como root
if [[ $EUID -ne 0 ]]; then
    echo "Este script necesita privilegios de root. Reintentando con sudo..."
    exec sudo DEV_ENV="$DEV_ENV" "$0" "$@"
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Si no se definió DEV_ENV, usar el directorio actual como valor por defecto
DEV_ENV="${DEV_ENV:-$(pwd)}"
export DEV_ENV

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $DEV_ENV -- grep: $grep"

runs_dir=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -executable)

for s in $runs_dir; do
    if basename "$s" | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi

    log "running script: $s"

    if [[ $dry_run == "0" ]]; then
        "$s"
    fi
done
