[app]
overall = { bg = "#161616" }

[mgr]
cwd = { fg = "#dce5e5" }

hovered = { bg = "#252525" }
preview_hovered = { bg = "#252525" }

find_keyword = { fg = "#161616", bg = "#e4c56b", bold = false }
find_position = { fg = "#dce5e5", bg = "#252525", bold = false }

marker_copied = { fg = "#5fc878", bg = "#5fc878" }
marker_cut = { fg = "#e66b80", bg = "#e66b80" }
marker_marked = { fg = "#b895de", bg = "#b895de" }
marker_selected = { fg = "#dce5e5", bg = "#303030" }

border_symbol = "│"
border_style = { fg = "#2a2a2a" }

[tabs]
active = { fg = "#dce5e5", bg = "#303030", bold = false }
inactive = { fg = "#626262", bg = "#1b1b1b" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#dce5e5", bg = "#252525", bold = false }
normal_alt = { fg = "#626262", bg = "#1b1b1b" }

select_main = { fg = "#dce5e5", bg = "#303030", bold = false }
select_alt = { fg = "#626262", bg = "#1b1b1b" }

unset_main = { fg = "#e66b80", bg = "#1b1b1b", bold = false }
unset_alt = { fg = "#626262", bg = "#1b1b1b" }

[indicator]
parent = { fg = "#4a4a4a" }
current = { bg = "#303030", bold = false }
preview = { fg = "#4a4a4a" }
padding = { open = " ", close = " " }

[status]
overall = { fg = "#626262", bg = "#1b1b1b" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#dce5e5", bold = false }
progress_normal = { fg = "#dce5e5", bg = "#252525" }
progress_error = { fg = "#e66b80", bg = "#252525" }

perm_sep = { fg = "#2a2a2a" }
perm_type = { fg = "#5aa6e6" }
perm_read = { fg = "#e4c56b" }
perm_write = { fg = "#e66b80" }
perm_exec = { fg = "#5fc878" }

[which]
cols = 3
mask = { bg = "#161616" }
cand = { fg = "#dce5e5" }
rest = { fg = "#626262" }
desc = { fg = "#4a4a4a" }
separator = "  "
separator_style = { fg = "#2a2a2a" }

[confirm]
border = { fg = "#2a2a2a" }
title = { fg = "#dce5e5" }
btn_yes = { fg = "#161616", bg = "#dce5e5", bold = false }
btn_no = { fg = "#626262", bg = "#252525" }
btn_labels = [ "  Yes  ", "  No  " ]

[spot]
border = { fg = "#2a2a2a" }

[notify]
title_info = { fg = "#dce5e5" }
title_warn = { fg = "#e4c56b" }
title_error = { fg = "#e66b80" }
icon_info = ""
icon_warn = ""
icon_error = ""

[pick]
border = { fg = "#2a2a2a" }
active = { fg = "#dce5e5", bg = "#303030" }
inactive = { fg = "#626262" }

[input]
border = { fg = "#2a2a2a" }
title = { fg = "#dce5e5" }
value = { fg = "#dce5e5" }
selected = { bg = "#303030" }

[cmp]
border = { fg = "#2a2a2a" }
active = { fg = "#dce5e5", bg = "#303030" }
inactive = { fg = "#626262" }

[tasks]
border = { fg = "#2a2a2a" }
hovered = { bg = "#252525" }

[help]
on = { fg = "#dce5e5" }
run = { fg = "#626262" }
desc = { fg = "#4a4a4a" }
hovered = { bg = "#252525" }
footer = { fg = "#4a4a4a", bg = "#161616" }

[filetype]
rules = [
    { url = "*/", fg = "#e5ecec", bold = false },
    { url = "*", fg = "#dce5e5" }
]

[icon]
globs = []
dirs = [
    { name = ".config", text = "", fg = "#e5ecec" },
    { name = ".git", text = "", fg = "#e5ecec" },
    { name = ".github", text = "", fg = "#e5ecec" },
    { name = "Desktop", text = "", fg = "#e5ecec" },
    { name = "Development", text = "", fg = "#e5ecec" },
    { name = "Documents", text = "", fg = "#e5ecec" },
    { name = "Downloads", text = "", fg = "#e5ecec" },
    { name = "Library", text = "", fg = "#e5ecec" },
    { name = "Movies", text = "", fg = "#e5ecec" },
    { name = "Music", text = "", fg = "#e5ecec" },
    { name = "Pictures", text = "", fg = "#e5ecec" },
    { name = "Public", text = "", fg = "#e5ecec" },
    { name = "Videos", text = "", fg = "#e5ecec" },
]
files = [
    { name = ".bash_profile", text = "", fg = "#5fc878" },
    { name = ".bashrc", text = "", fg = "#5fc878" },
    { name = ".git-blame-ignore-revs", text = "", fg = "#e66b80" },
    { name = ".gitattributes", text = "", fg = "#e66b80" },
    { name = ".gitconfig", text = "", fg = "#e66b80" },
    { name = ".gitignore", text = "", fg = "#e66b80" },
    { name = ".gitmodules", text = "", fg = "#e66b80" },
    { name = ".vimrc", text = "", fg = "#5fc878" },
    { name = ".zprofile", text = "", fg = "#5fc878" },
    { name = ".zshenv", text = "", fg = "#5fc878" },
    { name = ".zshrc", text = "", fg = "#5fc878" },
    { name = "docker-compose.yml", text = "󰡨", fg = "#5aa6e6" },
    { name = "docker-compose.yaml", text = "󰡨", fg = "#5aa6e6" },
    { name = "dockerfile", text = "󰡨", fg = "#5aa6e6" },
    { name = "license", text = "", fg = "#e4c56b" },
    { name = "license.md", text = "", fg = "#e4c56b" },
    { name = "makefile", text = "", fg = "#e4c56b" },
    { name = "package.json", text = "", fg = "#5fc878" },
    { name = "readme", text = "󰂺", fg = "#dce5e5" },
    { name = "readme.md", text = "󰂺", fg = "#dce5e5" },
    { name = "tsconfig.json", text = "", fg = "#5aa6e6" },
]
exts = [
    { name = "sh", text = "", fg = "#5fc878" },
    { name = "bash", text = "", fg = "#5fc878" },
    { name = "zsh", text = "", fg = "#5fc878" },
    { name = "fish", text = "", fg = "#5fc878" },
    { name = "ps1", text = "󰨊", fg = "#5aa6e6" },

    { name = "toml", text = "", fg = "#e4c56b" },
    { name = "yaml", text = "", fg = "#e4c56b" },
    { name = "yml", text = "", fg = "#e4c56b" },
    { name = "json", text = "", fg = "#e4c56b" },
    { name = "ini", text = "", fg = "#e4c56b" },
    { name = "conf", text = "", fg = "#e4c56b" },

    { name = "lua", text = "", fg = "#5aa6e6" },
    { name = "py", text = "", fg = "#e4c56b" },
    { name = "js", text = "", fg = "#e4c56b" },
    { name = "ts", text = "", fg = "#5aa6e6" },
    { name = "tsx", text = "", fg = "#5aa6e6" },
    { name = "jsx", text = "", fg = "#5aa6e6" },
    { name = "go", text = "", fg = "#5aa6e6" },
    { name = "rs", text = "", fg = "#e66b80" },
    { name = "c", text = "", fg = "#5aa6e6" },
    { name = "cpp", text = "", fg = "#5aa6e6" },
    { name = "cc", text = "", fg = "#5aa6e6" },
    { name = "h", text = "", fg = "#b895de" },
    { name = "hpp", text = "", fg = "#b895de" },
    { name = "vim", text = "", fg = "#5fc878" },

    { name = "css", text = "", fg = "#b895de" },
    { name = "scss", text = "", fg = "#b895de" },
    { name = "less", text = "", fg = "#b895de" },
    { name = "html", text = "", fg = "#e66b80" },
    { name = "htm", text = "", fg = "#e66b80" },

    { name = "csv", text = "", fg = "#5fc878" },
    { name = "md", text = "", fg = "#dce5e5" },
    { name = "markdown", text = "", fg = "#dce5e5" },
    { name = "txt", text = "󰈙", fg = "#626262" },
    { name = "log", text = "󰌱", fg = "#626262" },

    { name = "jpg", text = "", fg = "#eca25c" },
    { name = "jpeg", text = "", fg = "#eca25c" },
    { name = "png", text = "", fg = "#eca25c" },
    { name = "gif", text = "", fg = "#eca25c" },
    { name = "svg", text = "󰜡", fg = "#b895de" },
    { name = "webp", text = "", fg = "#eca25c" },
    { name = "ico", text = "", fg = "#eca25c" },
    { name = "mp3", text = "", fg = "#b895de" },
    { name = "mp4", text = "", fg = "#b895de" },
    { name = "webm", text = "", fg = "#b895de" },
    { name = "mkv", text = "", fg = "#b895de" },
    { name = "mov", text = "", fg = "#b895de" },
    { name = "wav", text = "", fg = "#b895de" },
    { name = "flac", text = "", fg = "#b895de" },
    { name = "ogg", text = "", fg = "#b895de" },

    { name = "zip", text = "", fg = "#e66b80" },
    { name = "tar", text = "", fg = "#e66b80" },
    { name = "gz", text = "", fg = "#e66b80" },
    { name = "tgz", text = "", fg = "#e66b80" },
    { name = "bz2", text = "", fg = "#e66b80" },
    { name = "xz", text = "", fg = "#e66b80" },
    { name = "7z", text = "", fg = "#e66b80" },
    { name = "rar", text = "", fg = "#e66b80" },
    { name = "deb", text = "", fg = "#e66b80" },
    { name = "rpm", text = "", fg = "#e66b80" },
    { name = "iso", text = "", fg = "#e66b80" },

    { name = "pdf", text = "", fg = "#eca25c" },
    { name = "doc", text = "󰈬", fg = "#5aa6e6" },
    { name = "docx", text = "󰈬", fg = "#5aa6e6" },
    { name = "xls", text = "󰈛", fg = "#5fc878" },
    { name = "xlsx", text = "󰈛", fg = "#5fc878" },
    { name = "ppt", text = "󰈬", fg = "#e66b80" },
    { name = "pptx", text = "󰈬", fg = "#e66b80" },
    { name = "epub", text = "", fg = "#eca25c" },

    { name = "ttf", text = "", fg = "#4a4a4a" },
    { name = "otf", text = "", fg = "#4a4a4a" },
    { name = "woff", text = "", fg = "#4a4a4a" },
    { name = "woff2", text = "", fg = "#4a4a4a" },

    { name = "git", text = "", fg = "#e66b80" },
    { name = "sqlite", text = "", fg = "#5aa6e6" },
    { name = "db", text = "", fg = "#5aa6e6" },
    { name = "sql", text = "", fg = "#5aa6e6" },

    { name = "exe", text = "", fg = "#5fc878" },
    { name = "bin", text = "", fg = "#5fc878" },

    { name = "lock", text = "", fg = "#626262" },
]
conds = [
    { if = "orphan", text = "", fg = "#e66b80" },
    { if = "link", text = "", fg = "#626262" },
    { if = "block", text = "", fg = "#4a4a4a" },
    { if = "char", text = "", fg = "#4a4a4a" },
    { if = "fifo", text = "", fg = "#4a4a4a" },
    { if = "sock", text = "", fg = "#4a4a4a" },
    { if = "sticky", text = "", fg = "#e4c56b" },
    { if = "dummy", text = "", fg = "#e66b80" },

    { if = "dir", text = "", fg = "#dce5e5" },
    { if = "exec", text = "", fg = "#5fc878" },
    { if = "!dir", text = "", fg = "#626262" },
]
