set -g status-justify left
set -g status-style "fg=#ABB2BF,bg=#31353F"
set -g pane-border-style "fg=#5C6370"
set -g pane-active-border-style "fg=#31353F"
set -g message-style "fg=#ABB2BF,bg=#31353F,bold"
set -g message-command-style "fg=#ABB2BF,bg=#31353F,bold"
set -g mode-style "bg=#393F4A"
set -g window-status-separator ""
set -g window-status-style "fg=#5C6370"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W* "
set -g window-status-current-style "fg=#ABB2BF,bold"
set -g status-left ""
set -g status-right "#[fg=#ABB2BF,bold] #S"
setw -g clock-mode-colour "#5C6370"
