palette = 0=#131618
palette = 1=#E0617A
palette = 2=#8FCF7A
palette = 3=#D9CC58
palette = 4=#A5E9F5
palette = 5=#D78CF0
palette = 6=#46C2A8
palette = 7=#E9F2F2

palette = 8=#33383C
palette = 9=#F1738D
palette = 10=#9FDC8A
palette = 11=#E6D667
palette = 12=#B7F2FC
palette = 13=#E39AF8
palette = 14=#5FD3BA
palette = 15=#F5FAFA

background = #181A1C
foreground = #E9F2F2
cursor-color = #E9F2F2
cursor-text = #181A1C
selection-background = #33383C
selection-foreground = #E9F2F2
