#!/usr/bin/env bash
set -e

# CommitMono20 is installed manually from https://commitmono.com
# with these custom settings (save as custom-settings.json before download):
#
#   {"weight":400,"italic":false,"alternates":{"cv01":false,"cv02":false,
#   "cv03":false,"cv04":false,"cv05":false,"cv06":false,"cv07":true,
#   "cv08":false,"cv09":false,"cv10":false,"cv11":false},"features":
#   {"ss01":false,"ss02":false,"ss03":true,"ss04":false,"ss05":true},
#   "letterSpacing":0,"lineHeight":1.2,"fontName":"20"}
#
# Install the 4 font files to ~/.local/share/fonts/CommitMono20/.

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

if [[ $EUID -eq 0 ]]; then
    REAL_USER="$SUDO_USER"
    REAL_HOME=$(eval echo "~$REAL_USER")
else
    REAL_USER="$USER"
    REAL_HOME="$HOME"
fi

FONT_DIR="$REAL_HOME/.local/share/fonts"
mkdir -p "$FONT_DIR"

NF_VERSION="v3.5.1"
NF_BASE="https://github.com/ryanoasis/nerd-fonts/releases/download/$NF_VERSION"

for font in GeistMono JetBrainsMono; do
    zip="$TMPDIR/$font.zip"
    curl -Lo "$zip" "$NF_BASE/$font.zip"
    unzip -o "$zip" -d "$FONT_DIR/$font"
done

fc-cache -f
