#!/usr/bin/env bash
set -e

sudo pacman -S --noconfirm zsh
hash -r

if ! command -v starship &>/dev/null; then
    sh -c "$(curl -sS https://starship.rs/install.sh)" -- --yes
fi

sudo chsh -s $(which zsh)
