let mapleader = "\<Space>"
nnoremap <leader>e :Explore<CR>

set incsearch
set ignorecase
set smartcase
set nohlsearch

set number
set relativenumber
set cursorline

set splitbelow
set splitright

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

set termguicolors
set signcolumn=yes
set scrolloff=8

set clipboard=unnamedplus

set noswapfile
set nobackup
set undofile

set isfname+=@-@
set guicursor=
set formatoptions-=o

syntax on
set background=dark
colorscheme paragon
