return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "main",
		lazy = false,
		build = ":TSUpdate",
		config = function()
			-- Setup de nvim-treesitter (solo si necesitas configurar install_dir)
			require("nvim-treesitter").setup({
				install_dir = vim.fn.stdpath("data") .. "/site",
			})

			-- Instalar parsers
			require("nvim-treesitter").install({
				"lua",
				"vim",
				"vimdoc",
				"query",
				"svelte",
				"python",
				"javascript",
				"typescript",
				"tsx",
				"go",
				"regex",
				"c",
				"html",
				"css",
				"json",
				"yaml",
				"cpp",
				"java",
				"c_sharp",
				"php",
				"ruby",
				"rust",
				"swift",
				"kotlin",
				"dart",
				"scala",
				"perl",
				"r",
				"julia",
				"zig",
				"haskell",
				"elixir",
				"erlang",
				"ocaml",
				"clojure",
				"sql",
				"toml",
				"markdown",
				"markdown_inline",
				"bash",
				"dockerfile",
			})

			-- Habilitar treesitter features automáticamente
			vim.api.nvim_create_autocmd("FileType", {
				pattern = {
					"lua",
					"vim",
					"vimdoc",
					"query",
					"svelte",
					"python",
					"javascript",
					"typescript",
					"tsx",
					"go",
					"regex",
					"c",
					"html",
					"css",
					"json",
					"yaml",
					"cpp",
					"java",
					"c_sharp",
					"php",
					"ruby",
					"rust",
					"swift",
					"kotlin",
					"dart",
					"scala",
					"perl",
					"r",
					"julia",
					"zig",
					"haskell",
					"elixir",
					"erlang",
					"ocaml",
					"clojure",
					"sql",
					"toml",
					"markdown",
					"markdown_inline",
					"bash",
					"dockerfile",
				},
				callback = function()
					vim.treesitter.start()
				end,
			})
		end,
	},
}
