return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"lua",
					"latex",
					"scss",
					"norg",
					"typst",
					"vue",
					"vim",
					"vimdoc",
					"query",
					"svelte",
					"python",
					"javascript",
					"typescript",
					"tsx",
					"rust",
					"go",
					"c",
					"cpp",
					"html",
					"css",
					"json",
					"yaml",
					"toml",
					"markdown",
					"markdown_inline",
					"bash",
					"regex",
					"dockerfile",
					"gitignore",
				},
				modules = {},
				ignore_install = {},
				sync_install = false,
				auto_install = true,
				highlight = {
					enable = true,
					additional_vim_regex_highlighting = false,
				},
			})
		end,
	},
}
