set -g status-justify left
set -g status-style "fg=#DCD7BA,bg=#2A2A37"
set -g pane-border-style "fg=#727169"
set -g pane-active-border-style "fg=#2A2A37"
set -g message-style "fg=#DCD7BA,bg=#2A2A37,bold"
set -g message-command-style "fg=#DCD7BA,bg=#2A2A37,bold"
set -g mode-style "bg=#2D4F67"
set -g window-status-separator ""
set -g window-status-style "fg=#727169"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W* "
set -g window-status-current-style "fg=#DCD7BA,bold"
set -g status-left ""
set -g status-right "#[fg=#DCD7BA,bold] #S"
setw -g clock-mode-colour "#727169"
