[general]
import = ["paragon.toml"]

[window]
opacity = 1.0
padding = { x = 0, y = 0 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrainsMono" }
size = 13

[cursor]
style = "Block"

[selection]
save_to_clipboard = true

[scrolling]
multiplier = 3

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "master"]

[mouse]
hide_when_typing = true
