[general]
import = ["rose-pine-moon.toml"]

[window]
opacity = 1.0
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono SemiBold" }
size = 14

[cursor]
style = "Block"

[selection]
save_to_clipboard = true

[scrolling]
multiplier = 3

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "master"]

[mouse]
hide_when_typing = true
