"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 
command_timeout = 200
format = "$hostname$directory$git_branch$git_status$character"

[character]
error_symbol   = "[›](bold #E66B80)"
success_symbol = "[›](bold #A1DEEA)"

[directory]
truncation_length = 3
truncation_symbol = "../"
style = "bold #B8D3D5"
repo_root_style = "bold #B8D3D5"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "#5C6870"

[git_branch]
format = "[$branch]($style) "
style = "#5C6870"

[git_status]
format = "[$conflicted](bold #E66B80)"
conflicted = "!"
