[mgr]
cwd = { fg = "#a9b1d6" }

hovered = { bg = "#292e42" }
preview_hovered = { bg = "#292e42" }

find_keyword = { fg = "#16161e", bg = "#ff9e64", bold = true }
find_position = { fg = "#0db9d7", bg = "#192b38", bold = true }

marker_copied = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut = { fg = "#f7768e", bg = "#f7768e" }
marker_marked = { fg = "#bb9af7", bg = "#bb9af7" }
marker_selected = { fg = "#7aa2f7", bg = "#7aa2f7" }

border_symbol = "│"
border_style = { fg = "#27a1b9" }

[tabs]
active = { fg = "#15161e", bg = "#7aa2f7", bold = true }
inactive = { fg = "#7aa2f7", bg = "#3b4261" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#15161e", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#3b4261" }

select_main = { fg = "#15161e", bg = "#bb9af7", bold = true }
select_alt = { fg = "#bb9af7", bg = "#3b4261" }

unset_main = { fg = "#15161e", bg = "#9d7cd8", bold = true }
unset_alt = { fg = "#9d7cd8", bg = "#3b4261" }

[indicator]
parent = { fg = "#545c7e" }
current = { bg = "#283457", bold = true }
preview = { fg = "#545c7e" }
padding = { open = " ", close = " " }

[status]
overall = { fg = "#c0caf5", bg = "#16161e" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#c0caf5", bold = true }
progress_normal = { fg = "#3d59a1", bg = "#292e42" }
progress_error = { fg = "#db4b4b", bg = "#292e42" }

perm_sep = { fg = "#414868" }
perm_type = { fg = "#7aa2f7" }
perm_read = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec = { fg = "#9ece6a" }

[which]
cols = 3
mask = { bg = "#16161e" }
cand = { fg = "#7dcfff" }
rest = { fg = "#7aa2f7" }
desc = { fg = "#bb9af7" }
separator = "  "
separator_style = { fg = "#565f89" }

[confirm]
border = { fg = "#0db9d7" }
title = { fg = "#27a1b9" }
btn_yes = { fg = "#15161e", bg = "#9ece6a", bold = true }
btn_no = { fg = "#c0caf5", bg = "#283457" }
btn_labels = [ "  Yes  ", "  No  " ]

[spot]
border = { fg = "#27a1b9" }

[notify]
title_info = { fg = "#0db9d7" }
title_warn = { fg = "#e0af68" }
title_error = { fg = "#db4b4b" }
icon_info = ""
icon_warn = ""
icon_error = ""

[pick]
border = { fg = "#27a1b9" }
active = { fg = "#c0caf5", bg = "#283457" }
inactive = { fg = "#565f89" }

[input]
border = { fg = "#0db9d7" }
title = { fg = "#0db9d7" }
value = { fg = "#9d7cd8" }
selected = { bg = "#283457" }

[cmp]
border = { fg = "#0db9d7" }
active = { fg = "#c0caf5", bg = "#343a55" }
inactive = { fg = "#565f89" }

[tasks]
border = { fg = "#27a1b9" }
hovered = { fg = "#c0caf5", bg = "#283457" }

[help]
on = { fg = "#9ece6a" }
run = { fg = "#bb9af7" }
desc = { fg = "#7dcfff" }
hovered = { bg = "#292e42" }
footer = { fg = "#c0caf5", bg = "#1a1b26" }

[filetype]
rules = [
    { url = "*/", fg = "#7aa2f7" },
    { url = "*", fg = "#c0caf5" }
]

[icon]
globs = []
dirs = [

    { name = ".config", text = "", fg = "#7aa2f7" },
    { name = ".git", text = "", fg = "#7aa2f7" },
    { name = ".github", text = "", fg = "#7aa2f7" },
    { name = "Desktop", text = "", fg = "#7aa2f7" },
    { name = "Development", text = "", fg = "#7aa2f7" },
    { name = "Documents", text = "", fg = "#7aa2f7" },
    { name = "Downloads", text = "", fg = "#7aa2f7" },
    { name = "Library", text = "", fg = "#7aa2f7" },
    { name = "Movies", text = "", fg = "#7aa2f7" },
    { name = "Music", text = "", fg = "#7aa2f7" },
    { name = "Pictures", text = "", fg = "#7aa2f7" },
    { name = "Public", text = "", fg = "#7aa2f7" },
    { name = "Videos", text = "", fg = "#7aa2f7" },
]
files = [
    { name = ".bash_profile", text = "", fg = "#9ece6a" },
    { name = ".bashrc", text = "", fg = "#9ece6a" },
    { name = ".git-blame-ignore-revs", text = "", fg = "#f7768e" },
    { name = ".gitattributes", text = "", fg = "#f7768e" },
    { name = ".gitconfig", text = "", fg = "#f7768e" },
    { name = ".gitignore", text = "", fg = "#f7768e" },
    { name = ".gitmodules", text = "", fg = "#f7768e" },
    { name = ".vimrc", text = "", fg = "#9ece6a" },
    { name = ".zprofile", text = "", fg = "#9ece6a" },
    { name = ".zshenv", text = "", fg = "#9ece6a" },
    { name = ".zshrc", text = "", fg = "#9ece6a" },
    { name = "docker-compose.yml", text = "󰡨", fg = "#7aa2f7" },
    { name = "docker-compose.yaml", text = "󰡨", fg = "#7aa2f7" },
    { name = "dockerfile", text = "󰡨", fg = "#7aa2f7" },
    { name = "license", text = "", fg = "#e0af68" },
    { name = "license.md", text = "", fg = "#e0af68" },
    { name = "makefile", text = "", fg = "#545c7e" },
    { name = "package.json", text = "", fg = "#e0af68" },
    { name = "readme", text = "󰂺", fg = "#7aa2f7" },
    { name = "readme.md", text = "󰂺", fg = "#7aa2f7" },
    { name = "tsconfig.json", text = "", fg = "#7aa2f7" },
]
exts = [
    { name = "sh", text = "", fg = "#9ece6a" },
    { name = "bash", text = "", fg = "#9ece6a" },
    { name = "zsh", text = "", fg = "#9ece6a" },
    { name = "fish", text = "", fg = "#9ece6a" },
    { name = "ps1", text = "󰨊", fg = "#7aa2f7" },

    { name = "toml", text = "", fg = "#ff9e64" },
    { name = "yaml", text = "", fg = "#bb9af7" },
    { name = "yml", text = "", fg = "#bb9af7" },
    { name = "json", text = "", fg = "#e0af68" },
    { name = "ini", text = "", fg = "#7aa2f7" },
    { name = "conf", text = "", fg = "#545c7e" },

    { name = "lua", text = "", fg = "#7aa2f7" },
    { name = "py", text = "", fg = "#7aa2f7" },
    { name = "js", text = "", fg = "#e0af68" },
    { name = "ts", text = "", fg = "#7aa2f7" },
    { name = "tsx", text = "", fg = "#7aa2f7" },
    { name = "jsx", text = "", fg = "#e0af68" },
    { name = "go", text = "", fg = "#7aa2f7" },
    { name = "rs", text = "", fg = "#ff9e64" },
    { name = "c", text = "", fg = "#7aa2f7" },
    { name = "cpp", text = "", fg = "#7aa2f7" },
    { name = "cc", text = "", fg = "#7aa2f7" },
    { name = "h", text = "", fg = "#7dcfff" },
    { name = "hpp", text = "", fg = "#7dcfff" },
    { name = "vim", text = "", fg = "#9ece6a" },

    { name = "css", text = "", fg = "#7dcfff" },
    { name = "scss", text = "", fg = "#7dcfff" },
    { name = "less", text = "", fg = "#7dcfff" },
    { name = "html", text = "", fg = "#ff9e64" },
    { name = "htm", text = "", fg = "#ff9e64" },

    { name = "csv", text = "", fg = "#e0af68" },
    { name = "md", text = "", fg = "#c0caf5" },
    { name = "markdown", text = "", fg = "#c0caf5" },
    { name = "txt", text = "󰈙", fg = "#565f89" },
    { name = "log", text = "󰌱", fg = "#565f89" },

    { name = "jpg", text = "", fg = "#bb9af7" },
    { name = "jpeg", text = "", fg = "#bb9af7" },
    { name = "png", text = "", fg = "#bb9af7" },
    { name = "gif", text = "", fg = "#bb9af7" },
    { name = "svg", text = "󰜡", fg = "#bb9af7" },
    { name = "webp", text = "", fg = "#bb9af7" },
    { name = "mp3", text = "", fg = "#bb9af7" },
    { name = "mp4", text = "", fg = "#f7768e" },
    { name = "webm", text = "", fg = "#f7768e" },
    { name = "wav", text = "", fg = "#bb9af7" },
    { name = "flac", text = "", fg = "#bb9af7" },
    { name = "ogg", text = "", fg = "#bb9af7" },

    { name = "zip", text = "", fg = "#f7768e" },
    { name = "tar", text = "", fg = "#f7768e" },
    { name = "gz", text = "", fg = "#f7768e" },
    { name = "tgz", text = "", fg = "#f7768e" },
    { name = "bz2", text = "", fg = "#f7768e" },
    { name = "7z", text = "", fg = "#f7768e" },
    { name = "rar", text = "", fg = "#f7768e" },

    { name = "pdf", text = "", fg = "#7dcfff" },
    { name = "doc", text = "󰈬", fg = "#7aa2f7" },
    { name = "docx", text = "󰈬", fg = "#7aa2f7" },
    { name = "xls", text = "󰈛", fg = "#9ece6a" },
    { name = "xlsx", text = "󰈛", fg = "#9ece6a" },
    { name = "ppt", text = "󰈧", fg = "#ff9e64" },
    { name = "pptx", text = "󰈧", fg = "#ff9e64" },

    { name = "ttf", text = "", fg = "#a9b1d6" },
    { name = "otf", text = "", fg = "#a9b1d6" },
    { name = "woff", text = "", fg = "#a9b1d6" },
    { name = "woff2", text = "", fg = "#a9b1d6" },

    { name = "git", text = "", fg = "#f7768e" },

    { name = "lock", text = "", fg = "#565f89" },
]
conds = [
    { if = "orphan", text = "", fg = "#f7768e" },
    { if = "link", text = "", fg = "#565f89" },
    { if = "block", text = "", fg = "#7dcfff" },
    { if = "char", text = "", fg = "#7dcfff" },
    { if = "fifo", text = "", fg = "#7dcfff" },
    { if = "sock", text = "", fg = "#7dcfff" },
    { if = "sticky", text = "", fg = "#e0af68" },
    { if = "dummy", text = "", fg = "#f7768e" },

    { if = "dir", text = "", fg = "#7aa2f7" },
    { if = "exec", text = "", fg = "#9ece6a" },
    { if = "!dir", text = "", fg = "#c0caf5" },
]
