"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 200
format = "$hostname$directory$git_branch$git_status$character"

[character]
error_symbol   = "[›](bold #F38BA8)"
success_symbol = "[›](bold #CBA6F7)"

[directory]
truncation_length = 3
truncation_symbol = "../"
style = "bold #CDD6F4"
repo_root_style = "bold #CDD6F4"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "#6C7086"

[git_branch]
format = "[$branch]($style) "
style = "#6C7086"

[git_status]
format = "[$conflicted](bold #F38BA8)"
conflicted = "!"
