set -g status-justify left
set -g status-style "fg=#CDD6F4,bg=#313244"
set -g pane-border-style "fg=#6C7086"
set -g pane-active-border-style "fg=#313244"
set -g message-style "fg=#CDD6F4,bg=#313244,bold"
set -g message-command-style "fg=#CDD6F4,bg=#313244,bold"
set -g mode-style "bg=#45475a"
set -g window-status-separator ""
set -g window-status-style "fg=#6C7086"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W* "
set -g window-status-current-style "fg=#CDD6F4,bold"
set -g status-left ""
set -g status-right "#[fg=#CDD6F4,bold] #S"
setw -g clock-mode-colour "#6C7086"
