# file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf
# If set this override the default TS_SEARCH_PATHS (~/ ~/personal ~/personal/dev/env/.config)
# TS_EXTRA_SEARCH_PATHS=(~/personal:3)
# TS_MAX_DEPTH=2

TS_SEARCH_PATHS=(~/:1 ~/personal/:3 ~/personal/dev/env/.config/:1)
